name: Search Repositories for Code String

on:
  workflow_dispatch:
    inputs:
      search_string:
        description: 'Text string to search for in code'
        required: true

jobs:
  search_code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code (optional)
        uses: actions/checkout@v2

      - name: Create repository URL list with pagination
        id: search
        run: |
          echo "Searching for repositories with code containing: ${{ github.event.inputs.search_string }}"
          rm -f repositories.txt
          page=1
          max_pages=10  # GitHub search API limits results to 1000 (10 pages * 100 per page)
          while [ $page -le $max_pages ]; do
            echo "Fetching page $page..."
            response=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
              "https://api.github.com/search/code?q=${{ github.event.inputs.search_string }}&per_page=100&page=$page")
            count=$(echo "$response" | jq '.items | length')
            if [ "$count" -eq 0 ]; then
              echo "No more results on page $page. Exiting loop."
              break
            fi
            # Append repository full names from current page
            echo "$response" | jq -r '.items[].repository.full_name' >> repositories.txt
            page=$((page + 1))
          done
          # Remove duplicates and sort results
          sort -u repositories.txt -o repositories.txt
          if [ -s repositories.txt ]; then
            echo "Found repositories:"
            cat repositories.txt
          else
            echo "No repositories found."
          fi

      - name: Display Repository URLs
        run: |
          echo "Repository URLs:"
          if [ -s repositories.txt ]; then
            while read repo; do
              echo "https://github.com/$repo"
            done < repositories.txt
          else
            echo "No repository URLs to display."
          fi
